// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import "./PoolRoundTestBase.sol";

/**
 * (d) Replays one book settled by scripts/rhc/positive-ev.mts through PoolRounds
 * and compares everything the reference computes. The vectors themselves are in
 * PoolRoundVectors.t.sol, generated by scripts/rhc/PoolRoundVectors.mts.
 *
 * Vector layout (abi-encoded uint256[]):
 *   w[0] = n | outcome << 8 | active << 16 | ratio << 24   outcome 1 up, 2 down, 3 tie, 4 oracle refund
 *   w[1] = cost allowance, w[2] = minimum bank  (the reference's policy for that gas price)
 *   w[3] = bank, w[4] = gross fee, w[5] = referral, w[6] = treasury, w[7] = dust
 *   w[8 + i] = up << 255 | stake << 128 | payout
 *
 * Each vector gets its own PoolRounds with the vector's side cap (it is
 * immutable). Every player has the same referrer, as the reference assumes
 * ("every unit of fee has a referrer"), so the project's part must equal the
 * reference's treasury exactly. The referrer receives the reference's referral
 * minus the rounding of the per-ticket split (< 1 wei per ticket), which stays
 * as dust.
 */
abstract contract PoolRoundVectorsBase is PoolRoundTestBase {
    address internal constant REFERRER = address(0x7EFE7);
    uint256 internal constant LOW127 = (uint256(1) << 127) - 1;
    uint256 internal constant LOW128 = (uint256(1) << 128) - 1;

    function _check(bytes memory data) internal {
        uint256[] memory w = abi.decode(data, (uint256[]));
        uint256 n = w[0] & 0xff;
        uint256 outcome = (w[0] >> 8) & 0xff;
        bool active = (w[0] >> 16) & 1 == 1;
        uint256 ratio = (w[0] >> 24) & 0xff;
        assertEq(w.length, 8 + n, "vector length");

        _useRatio(ratio);
        rounds.setCostAllowance(w[1]);
        rounds.setMinBank(w[2]);
        PoolRoundMockPool p = pool;
        uint256 id = _nextRound(p, T);
        for (uint256 i = 0; i < n; i++) {
            _bet(id, _player(i), (w[8 + i] >> 128) & LOW127, w[8 + i] >> 255 == 1 ? _up() : _down(), REFERRER);
        }
        if (outcome == 1) _exitTick(p, id, 100);
        if (outcome == 2) _exitTick(p, id, -100);
        _warpSettle(id);

        assertEq(rounds.roundView(id).activated, active, "activation");
        if (active) {
            if (outcome == 4) p.setForceOld(true);
            rounds.settle(id);
            assertEq(uint256(rounds.roundView(id).outcome), outcome, "outcome");
            assertEq(rounds.roundView(id).bank, w[3], "accepted bank");
            assertEq(rounds.feesAccrued(), w[6], "project part of the fee = reference treasury");
        } else {
            vm.expectRevert(abi.encodeWithSelector(PoolRounds.NotActivated.selector, id));
            rounds.settle(id);
        }

        uint256 paid;
        for (uint256 i = 0; i < n; i++) {
            uint256 got = _claim(id, _player(i));
            assertEq(got, w[8 + i] & LOW128, "payout of ticket i");
            paid += got;
        }

        uint256 fees = rounds.feesAccrued();
        uint256 toReferrer = rounds.referralOwed(REFERRER);
        uint256 left = weth.balanceOf(address(rounds));
        assertEq(fees, w[6], "no referral share fell back to the treasury");
        assertLe(toReferrer, w[5], "referrer never gets more than the reference");
        if (active) assertLt(w[5] - toReferrer, n + 1, "split rounding < 1 wei per ticket");
        else assertEq(toReferrer, 0);
        assertEq(left, fees + toReferrer + w[7] + (w[5] - toReferrer), "left inside = fee + reference dust");
        assertEq(paid + w[4] + w[7], _sumStakes(w, n), "reference conservation, replayed");
    }

    function _sumStakes(uint256[] memory w, uint256 n) internal pure returns (uint256 s) {
        for (uint256 i = 0; i < n; i++) {
            s += (w[8 + i] >> 128) & LOW127;
        }
    }
}
