/**
 * Referral-code capture — Sprint 5.5 audit fix.
 *
 * Before this, `?ref=CODE` links (generated by Portfolio's ReferralPanel)
 * were never read anywhere: nothing captured the code, resolved it to a
 * referrer address, or passed it into placeBet. The entire referral loop
 * (40% of the protocol fee!) was dead on arrival. This closes that gap.
 */

const STORAGE_KEY = 'flipthememe:pendingReferrer'
const ZERO_ADDRESS = '0x0000000000000000000000000000000000000000'

/**
 * Reads `?ref=CODE` from the current URL (if present), resolves it to a
 * referrer address via the backend, and persists the address so it
 * survives across sessions until the user actually places a bet. Call once
 * on app mount. Best-effort: never throws, never blocks rendering.
 */
export function captureReferralCode(): void {
  const code = new URLSearchParams(window.location.search).get('ref')
  if (!code) return

  const api = import.meta.env.VITE_API_URL
  if (!api) return

  fetch(`${api}/api/referral/resolve/${code}`)
    .then((res) => (res.ok ? res.json() : null))
    .then((json: { referrer?: string } | null) => {
      if (json?.referrer) {
        localStorage.setItem(STORAGE_KEY, json.referrer)
      }
    })
    .catch(() => {
      // Referral capture is best-effort — a failed resolve must never
      // block the app or surface an error to the user.
    })
}

/**
 * The persisted referrer address, if any was captured this session or before.
 *
 * Pass the connected account so a self-referral can be dropped. The contract
 * enforces `require(referrer != msg.sender, "self referral")` as a hard revert
 * in _placeBet, and the stored referrer was never compared to the wallet — so
 * opening your own share link (the first thing anyone does after generating
 * one; Portfolio renders it as `/?ref=<yourCode>`) permanently poisoned
 * localStorage and made every subsequent bet from that browser revert, after
 * the user had already signed and paid for the USDC approve.
 */
export function getPendingReferrer(self?: `0x${string}` | null): `0x${string}` {
  const stored = localStorage.getItem(STORAGE_KEY)
  if (!stored) return ZERO_ADDRESS as `0x${string}`
  if (self && stored.toLowerCase() === self.toLowerCase()) return ZERO_ADDRESS as `0x${string}`
  return stored as `0x${string}`
}
